name: Deployment Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      name: testing ssh connection
      with:
        host: ${{ secrets.WRAPPER_HOST }}
        username: ${{ secrets.WRAPPER_USERNAME }}
        key: ${{ secrets.WRAPPER_KEY }}
        port: 22
        script: |
          cd bitcou-wrapper
          git pull origin main
          docker-compose -f wrapper-app-compose.yaml up --build -d
          docker rmi $(docker images -f dangling=true -q)
